image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
  - python setup.py test
  - pip install tox flake8
  - tox -e py36,flake8

run:
  script:
  - python setup.py bdist_wheel
  artifacts:
    paths:
    - dist/*.whl
