image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt-get install unixodbc-dev python3-dev
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
  - python setup.py test

run:
  script:
  - python setup.py bdist_wheel
  artifacts:
    paths:
    - dist/*.whl
